# -*- coding: utf-8 -*-
"""Text generation model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EIS6vAO_MeOStoy-BL3EFO8soh0TktA1
"""

# Install transformers library
!pip install transformers

# Import library
from transformers import pipeline

# Load GPT-2 model
generator = pipeline('text-generation', model='gpt2')

# Ask for user input
user_prompt = input("Enter a topic you want a paragraph about: ")

# Generate text
generated_text = generator(user_prompt, max_length=150, num_return_sequences=1, temperature=0.7)

# Print generated paragraph
print("\nGenerated Paragraph:\n")
print(generated_text[0]['generated_text'])