# -*- coding: utf-8 -*-
"""Text  summarization tool

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kML6zzb8ktzcIo20CISACLBomkGASr9q
"""

from transformers import pipeline
import os

# Load the NLP summarizer pipeline
summarizer = pipeline("summarization")

def read_text_file(file_path):
    if not os.path.exists(file_path):
        raise FileNotFoundError("File does not exist.")
    if not file_path.endswith('.txt'):
        raise ValueError("Only .txt files are supported.")

    with open(file_path, 'r', encoding='utf-8') as file:
        return file.read()

def summarize_text(text, min_len=30, max_len=150):
    if len(text) > 4000:
        text = text[:4000]  # Cut off long text to avoid input limits
    summary = summarizer(text, max_length=max_len, min_length=min_len, do_sample=False)
    return summary[0]['summary_text']

def main():
    print("Choose input method:")
    print("1. Enter text manually")
    print("2. Provide path to a .txt file")
    choice = input("Enter 1 or 2: ").strip()

    try:
        if choice == '1':
            input_text = input("\nEnter your text:\n")
        elif choice == '2':
            file_path = input("\nEnter the path to your .txt file: ").strip()
            input_text = read_text_file(file_path)
        else:
            print("Invalid choice.")
            return

        print("\nSummarizing content...\n")
        summary = summarize_text(input_text)

        print("=== SUMMARY ===")
        print(summary)

    except Exception as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    main()